services:
  traefik:
    image: traefik:3.3.4
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`dashboard.traefik.me`)"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=api-auth"
      - "traefik.http.middlewares.api-auth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/" # test:test

  redis:
    image: redis/redis-stack:7.4.0-v3
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data
      - redisinsight_data:/redisinsight
    labels:
      - "traefik.http.routers.redis.rule=Host(`redis.traefik.me`)"
      - "traefik.http.services.redis.loadbalancer.server.port=8001"

volumes:
  redis_data:
  redisinsight_data: