name: event-demo-dev
include:
  - path:
      - parts/docker-compose-databases.yaml
      - parts/docker-compose-databases-expose.yaml
      - parts/docker-compose-tools.yaml
      - parts/docker-compose-tools-local.yaml
      - parts/docker-compose-traefik.yaml

services:
  postgresql:
    environment:
      POSTGRES_PASSWORD: "changeit"

  pgadmin:
    environment:
      PGADMIN_DEFAULT_PASSWORD: "changeit"