name: event-demo-test
include:
  - path:
    - parts/docker-compose-databases.yaml
    - parts/docker-compose-test.yaml
    - parts/docker-compose-traefik.yaml

services:
  postgresql:
    environment:
      POSTGRES_PASSWORD: "changeit"