services:
  flyway:
    image: flyway/flyway
    command: migrate
    depends_on:
      postgresql:
        condition: service_healthy
    volumes:
      - ../../migrations/events:/flyway/sql
      - ../flyway.conf:/flyway/conf/flyway.conf
    restart: no

  postgresql:
    image: postgres:18.4
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_USER: event-demo
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U event-demo'"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - postgresql_data:/var/lib/postgresql

  rabbitmq:
    image: rabbitmq:4-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: event-demo
      RABBITMQ_DEFAULT_PASS: changeit
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/

volumes:
  postgresql_data:
  rabbitmq_data: