services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
    secrets:
      - pgadmin_password
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    labels:
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.postgresql.traefik.me`)"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"

  redis:
    labels:
      - "traefik.http.routers.redisinsight.rule=Host(`insight.redis.traefik.me`)"
      - "traefik.http.routers.redisinsight.service=redisinsight"
      - "traefik.http.services.redisinsight.loadbalancer.server.port=8001"

  rabbitmq:
    labels:
      - "traefik.http.routers.rabbitmq-management.rule=Host(`management.rabbitmq.traefik.me`)"
      - "traefik.http.routers.rabbitmq-management.service=rabbitmq-management"
      - "traefik.http.services.rabbitmq-management.loadbalancer.server.port=15672"

secrets:
  pgadmin_password:
    file: ../pgadmin.secret

volumes:
  pgadmin_data: