services:
  app:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    depends_on:
      flyway:
        condition: service_completed_successfully
      postgresql:
        condition: service_healthy
