services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@event-demo.dev}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    configs:
      - source: servers_json
        target: /pgadmin4/servers.json
    labels:
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.postgresql.traefik.me`)"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"

  rabbitmq:
    labels:
      - "traefik.http.routers.rabbitmq-management.rule=Host(`management.rabbitmq.traefik.me`)"
      - "traefik.http.routers.rabbitmq-management.service=rabbitmq-management"
      - "traefik.http.services.rabbitmq-management.loadbalancer.server.port=15672"

configs:
  servers_json:
    content: |
      {
        "Servers": {
          "1": {
            "Name": "Event demo",
            "Group": "Servers",
            "Host": "postgresql",
            "Port": 5432,
            "MaintenanceDB": "event-demo",
            "Username": "event-demo",
            "PassFile": "/pgpass",
            "SSLMode": "prefer"
          }
        }
      }

volumes:
  pgadmin_data: