services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
    secrets:
      - pgadmin_password
    volumes:
      - pgadmin_data:/var/lib/pgadmin

secrets:
  pgadmin_password:
    file: ../pgadmin.secret

volumes:
  pgadmin_data: