services:
  api:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    depends_on:
      flyway:
        condition: service_completed_successfully
      postgresql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    labels:
      - "traefik.http.routers.api.rule=Host(`api.traefik.me`)"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
